apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  labels:
    app: ollama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama-container
        image: ollama:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: PROMETHEUS_MONITORING
          value: "enabled"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
